/*********************************************************************************************************
* 文件名：GUI.H
* 功能：
* 作者：黄绍斌
* 日期：2004.03.11
* 备注：。
*********************************************************************************************************/
#ifndef  GUI_H
#define  GUI_H


#include    "..\ZLG_GUI\GUI_CONFIG.H"
#include    "..\ZLG_GUI\GUI_STOCKC.H"
#include    "..\ZLG_GUI\GUI_BASIC.H"
#include    "..\ZLG_GUI\FONT_MACRO.H"
#include    "..\ZLG_GUI\FONT5_7.H"
#include    "..\ZLG_GUI\FONT8_8.H"
#include    "..\ZLG_GUI\FONT8_16.H"
#include    "..\ZLG_GUI\FONT24_32.H"
#include    "..\ZLG_GUI\LOADBIT.H"
#include    "..\ZLG_GUI\WINDOWS.H"
#include    "..\ZLG_GUI\MENU.H"
#include    "..\ZLG_GUI\spline.H"

#include    "..\ZLG_GUI\Font16.h"
#include    "..\ZLG_GUI\lcddrive.H"
#endif
